export const COLOR_PRIMARY = "#FAB836"
export const COLOR_SECONDARY = "#F2A100"
export const COLOR_INACTIVE = "#C2C2C2"
export const COLOR_BACKGROUND_ICON = "#F2DAAC"
export const COLOR_WHITE = "#FFFFFF"
export const COLOR_BLACK = "#000000"